# Generated by Django 2.2.18 on 2022-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
