# Generated by Django 3.0.4 on 2022-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_result_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='questions',
            field=models.ManyToManyField(blank=True, to='App.Question'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='App.Chapter'),
        ),
    ]
