# Generated by Django 3.0.4 on 2022-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_test_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
